
clear all; clc;
P1_values = [0.01 0.1 1.0 10.0 100.0];
% List of all CSV files generated by MOOSE
csv_files = {'CDM_module_uniaxial_loading_P0.01_out.csv', ...
              'CDM_module_uniaxial_loading_P0.1_out.csv', ...
              'CDM_module_uniaxial_loading_P1_out.csv', ...
              'CDM_module_uniaxial_loading_P10_out.csv', ...
              'CDM_module_uniaxial_loading_P100_out.csv', ...
              };

% Create an empty table
combined_table = table();

figure;
hold on;

% Iterate over each CSV file and append it to the combined table
for i = 1:length(csv_files)

    P1 = P1_values(i);
    % Read the CSV file
    file_name = csv_files{i};
    T = readtable(file_name);
    
    stress = T.stress;
    strain = T.strain;

    plot(strain,stress, 'Linewidth', 2, 'DisplayName', ['P1 = ' num2str(P1)]);
end

title('Stress - Strain Curve');
xlabel('Strain');
ylabel('Stress');
colormap;
grid on;
hold off;